// Code generated by github.com/cshum/vipsgen from libvips 8.16.1; DO NOT EDIT.

#include <stdlib.h>
#include <vips/vips.h>
#include <vips/vector.h>

// Prerequisites to build, get outputs and cleanup a vips operation

int vipsgen_operation_execute(VipsOperation *operation, ...);
int vipsgen_operation_save_buffer(VipsOperation *operation, void** buf, size_t* len);
int vipsgen_set_source(VipsOperation *operation, const char *name, VipsSource *value);
int vipsgen_set_target(VipsOperation *operation, const char *name, VipsTarget *value);
int vipsgen_set_int(VipsOperation *operation, const char *name, int value);
int vipsgen_set_bool(VipsOperation *operation, const char *name, gboolean value);
int vipsgen_set_double(VipsOperation *operation, const char *name, double value);
int vipsgen_set_guint64(VipsOperation *operation, const char *name, guint64 value);
int vipsgen_set_string(VipsOperation *operation, const char *name, const char *value);
int vipsgen_set_image(VipsOperation *operation, const char *name, VipsImage *value);
int vipsgen_set_array_double(VipsOperation *operation, const char *name, VipsArrayDouble *value);
int vipsgen_set_array_int(VipsOperation *operation, const char *name, VipsArrayInt *value);
int vipsgen_set_array_image(VipsOperation *operation, const char *name, VipsArrayImage *value);
int vipsgen_set_interpolate(VipsOperation *operation, const char *name, VipsInterpolate *value);

// Generated operations

int vipsgen_CMC2LCh(VipsImage* in, VipsImage** out);

int vipsgen_CMYK2XYZ(VipsImage* in, VipsImage** out);

int vipsgen_HSV2sRGB(VipsImage* in, VipsImage** out);

int vipsgen_LCh2CMC(VipsImage* in, VipsImage** out);

int vipsgen_LCh2Lab(VipsImage* in, VipsImage** out);

int vipsgen_Lab2LCh(VipsImage* in, VipsImage** out);

int vipsgen_Lab2LabQ(VipsImage* in, VipsImage** out);

int vipsgen_Lab2LabS(VipsImage* in, VipsImage** out);

int vipsgen_Lab2XYZ(VipsImage* in, VipsImage** out);
int vipsgen_Lab2XYZ_with_options(VipsImage* in, VipsImage** out, double* temp, int temp_n);

int vipsgen_LabQ2Lab(VipsImage* in, VipsImage** out);

int vipsgen_LabQ2LabS(VipsImage* in, VipsImage** out);

int vipsgen_LabQ2sRGB(VipsImage* in, VipsImage** out);

int vipsgen_LabS2Lab(VipsImage* in, VipsImage** out);

int vipsgen_LabS2LabQ(VipsImage* in, VipsImage** out);

int vipsgen_XYZ2CMYK(VipsImage* in, VipsImage** out);

int vipsgen_XYZ2Lab(VipsImage* in, VipsImage** out);
int vipsgen_XYZ2Lab_with_options(VipsImage* in, VipsImage** out, double* temp, int temp_n);

int vipsgen_XYZ2Yxy(VipsImage* in, VipsImage** out);

int vipsgen_XYZ2scRGB(VipsImage* in, VipsImage** out);

int vipsgen_Yxy2XYZ(VipsImage* in, VipsImage** out);

int vipsgen_abs(VipsImage* in, VipsImage** out);

int vipsgen_add(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_addalpha(VipsImage* in, VipsImage** out);

int vipsgen_affine(VipsImage* in, VipsImage** out, double a, double b, double c, double d);
int vipsgen_affine_with_options(VipsImage* in, VipsImage** out, double a, double b, double c, double d, VipsInterpolate* interpolate, int* oarea, int oarea_n, double odx, double ody, double idx, double idy, double* background, int background_n, gboolean premultiplied, VipsExtend extend);

int vipsgen_analyzeload(const char* filename, VipsImage** out);
int vipsgen_analyzeload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_arrayjoin(VipsImage** in, VipsImage** out, int n);
int vipsgen_arrayjoin_with_options(VipsImage** in, VipsImage** out, int n, int across, int shim, double* background, int background_n, VipsAlign halign, VipsAlign valign, int hspacing, int vspacing);

int vipsgen_autorot(VipsImage* in, VipsImage** out);

int vipsgen_avg(VipsImage* in, double* out);

int vipsgen_bandbool(VipsImage* in, VipsImage** out, VipsOperationBoolean boolean);

int vipsgen_bandfold(VipsImage* in, VipsImage** out);
int vipsgen_bandfold_with_options(VipsImage* in, VipsImage** out, int factor);

int vipsgen_bandjoin(VipsImage** in, VipsImage** out, int n);

int vipsgen_bandjoin_const(VipsImage* in, VipsImage** out, double* c, int n);

int vipsgen_bandmean(VipsImage* in, VipsImage** out);

int vipsgen_bandrank(VipsImage** in, VipsImage** out, int n);
int vipsgen_bandrank_with_options(VipsImage** in, VipsImage** out, int n, int index);

int vipsgen_bandunfold(VipsImage* in, VipsImage** out);
int vipsgen_bandunfold_with_options(VipsImage* in, VipsImage** out, int factor);

int vipsgen_black(VipsImage** out, int width, int height);
int vipsgen_black_with_options(VipsImage** out, int width, int height, int bands);

int vipsgen_boolean(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationBoolean boolean);

int vipsgen_boolean_const(VipsImage* in, VipsImage** out, VipsOperationBoolean boolean, double* c, int n);

int vipsgen_buildlut(VipsImage* in, VipsImage** out);

int vipsgen_byteswap(VipsImage* in, VipsImage** out);

int vipsgen_canny(VipsImage* in, VipsImage** out);
int vipsgen_canny_with_options(VipsImage* in, VipsImage** out, double sigma, VipsPrecision precision);

int vipsgen_case(VipsImage* index, VipsImage** cases, VipsImage** out, int n);

int vipsgen_cast(VipsImage* in, VipsImage** out, VipsBandFormat format);
int vipsgen_cast_with_options(VipsImage* in, VipsImage** out, VipsBandFormat format, gboolean shift);

int vipsgen_clamp(VipsImage* in, VipsImage** out);
int vipsgen_clamp_with_options(VipsImage* in, VipsImage** out, double min, double max);

int vipsgen_colourspace(VipsImage* in, VipsImage** out, VipsInterpretation space);
int vipsgen_colourspace_with_options(VipsImage* in, VipsImage** out, VipsInterpretation space, VipsInterpretation source_space);

int vipsgen_compass(VipsImage* in, VipsImage** out, VipsImage* mask);
int vipsgen_compass_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, int times, VipsAngle45 angle, VipsCombine combine, VipsPrecision precision, int layers, int cluster);

int vipsgen_complex(VipsImage* in, VipsImage** out, VipsOperationComplex cmplx);

int vipsgen_complex2(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationComplex2 cmplx);

int vipsgen_complexform(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_complexget(VipsImage* in, VipsImage** out, VipsOperationComplexget get);

int vipsgen_composite(VipsImage** in, VipsImage** out, int n, int* mode);
int vipsgen_composite_with_options(VipsImage** in, VipsImage** out, int n, int* mode, int* x, int x_n, int* y, int y_n, VipsInterpretation compositing_space, gboolean premultiplied);

int vipsgen_composite2(VipsImage* base, VipsImage* overlay, VipsImage** out, VipsBlendMode mode);
int vipsgen_composite2_with_options(VipsImage* base, VipsImage* overlay, VipsImage** out, VipsBlendMode mode, int x, int y, VipsInterpretation compositing_space, gboolean premultiplied);

int vipsgen_conv(VipsImage* in, VipsImage** out, VipsImage* mask);
int vipsgen_conv_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, VipsPrecision precision, int layers, int cluster);

int vipsgen_conva(VipsImage* in, VipsImage** out, VipsImage* mask);
int vipsgen_conva_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, int layers, int cluster);

int vipsgen_convasep(VipsImage* in, VipsImage** out, VipsImage* mask);
int vipsgen_convasep_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, int layers);

int vipsgen_convf(VipsImage* in, VipsImage** out, VipsImage* mask);

int vipsgen_convi(VipsImage* in, VipsImage** out, VipsImage* mask);

int vipsgen_convsep(VipsImage* in, VipsImage** out, VipsImage* mask);
int vipsgen_convsep_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, VipsPrecision precision, int layers, int cluster);

int vipsgen_copy(VipsImage* in, VipsImage** out);
int vipsgen_copy_with_options(VipsImage* in, VipsImage** out, int width, int height, int bands, VipsBandFormat format, VipsCoding coding, VipsInterpretation interpretation, double xres, double yres, int xoffset, int yoffset);

int vipsgen_countlines(VipsImage* in, double* nolines, VipsDirection direction);

int vipsgen_csvload(const char* filename, VipsImage** out);
int vipsgen_csvload_with_options(const char* filename, VipsImage** out, int skip, int lines, const char* whitespace, const char* separator, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_csvload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_csvload_source_with_options(VipsSourceCustom* source, VipsImage** out, int skip, int lines, const char* whitespace, const char* separator, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_csvsave(VipsImage* in, const char* filename);
int vipsgen_csvsave_with_options(VipsImage* in, const char* filename, const char* separator, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_csvsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_csvsave_target_with_options(VipsImage* in, VipsTargetCustom* target, const char* separator, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_dE00(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_dE76(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_dECMC(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_deviate(VipsImage* in, double* out);

int vipsgen_divide(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_draw_circle(VipsImage* image, double* ink, int n, int cx, int cy, int radius);
int vipsgen_draw_circle_with_options(VipsImage* image, double* ink, int n, int cx, int cy, int radius, gboolean fill);

int vipsgen_draw_flood(VipsImage* image, double* ink, int n, int x, int y);
int vipsgen_draw_flood_with_options(VipsImage* image, double* ink, int n, int x, int y, VipsImage* test, gboolean equal);

int vipsgen_draw_image(VipsImage* image, VipsImage* sub, int x, int y);
int vipsgen_draw_image_with_options(VipsImage* image, VipsImage* sub, int x, int y, VipsCombineMode mode);

int vipsgen_draw_line(VipsImage* image, double* ink, int n, int x1, int y1, int x2, int y2);

int vipsgen_draw_mask(VipsImage* image, double* ink, int n, VipsImage* mask, int x, int y);

int vipsgen_draw_rect(VipsImage* image, double* ink, int n, int left, int top, int width, int height);
int vipsgen_draw_rect_with_options(VipsImage* image, double* ink, int n, int left, int top, int width, int height, gboolean fill);

int vipsgen_draw_smudge(VipsImage* image, int left, int top, int width, int height);

int vipsgen_embed(VipsImage* in, VipsImage** out, int x, int y, int width, int height);
int vipsgen_embed_with_options(VipsImage* in, VipsImage** out, int x, int y, int width, int height, VipsExtend extend, double* background, int background_n);

int vipsgen_extract_area(VipsImage* input, VipsImage** out, int left, int top, int width, int height);

int vipsgen_extract_band(VipsImage* in, VipsImage** out, int band);
int vipsgen_extract_band_with_options(VipsImage* in, VipsImage** out, int band, int n);

int vipsgen_eye(VipsImage** out, int width, int height);
int vipsgen_eye_with_options(VipsImage** out, int width, int height, gboolean uchar, double factor);

int vipsgen_falsecolour(VipsImage* in, VipsImage** out);

int vipsgen_fastcor(VipsImage* in, VipsImage* ref, VipsImage** out);

int vipsgen_fill_nearest(VipsImage* in, VipsImage** out);

int vipsgen_find_trim(VipsImage* in, int* left, int* top, int* width, int* height);
int vipsgen_find_trim_with_options(VipsImage* in, int* left, int* top, int* width, int* height, double threshold, double* background, int background_n, gboolean line_art);

int vipsgen_flatten(VipsImage* in, VipsImage** out);
int vipsgen_flatten_with_options(VipsImage* in, VipsImage** out, double* background, int background_n, double max_alpha);

int vipsgen_flip(VipsImage* in, VipsImage** out, VipsDirection direction);

int vipsgen_float2rad(VipsImage* in, VipsImage** out);

int vipsgen_fractsurf(VipsImage** out, int width, int height, double fractal_dimension);

int vipsgen_freqmult(VipsImage* in, VipsImage* mask, VipsImage** out);

int vipsgen_gamma(VipsImage* in, VipsImage** out);
int vipsgen_gamma_with_options(VipsImage* in, VipsImage** out, double exponent);

int vipsgen_gaussblur(VipsImage* in, VipsImage** out, double sigma);
int vipsgen_gaussblur_with_options(VipsImage* in, VipsImage** out, double sigma, double min_ampl, VipsPrecision precision);

int vipsgen_gaussmat(VipsImage** out, double sigma, double min_ampl);
int vipsgen_gaussmat_with_options(VipsImage** out, double sigma, double min_ampl, gboolean separable, VipsPrecision precision);

int vipsgen_gaussnoise(VipsImage** out, int width, int height);
int vipsgen_gaussnoise_with_options(VipsImage** out, int width, int height, double sigma, double mean, int seed);

int vipsgen_getpoint(VipsImage* in, double** out_array, int* n, int x, int y);
int vipsgen_getpoint_with_options(VipsImage* in, double** out_array, int* n, int x, int y, gboolean unpack_complex);

int vipsgen_gifload(const char* filename, VipsImage** out);
int vipsgen_gifload_with_options(const char* filename, VipsImage** out, int n, int page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_gifload_buffer(void* buf, size_t len, VipsImage** out);
int vipsgen_gifload_buffer_with_options(void* buf, size_t len, VipsImage** out, int n, int page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_gifload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_gifload_source_with_options(VipsSourceCustom* source, VipsImage** out, int n, int page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_globalbalance(VipsImage* in, VipsImage** out);
int vipsgen_globalbalance_with_options(VipsImage* in, VipsImage** out, double gamma, gboolean int_output);

int vipsgen_gravity(VipsImage* in, VipsImage** out, VipsCompassDirection direction, int width, int height);
int vipsgen_gravity_with_options(VipsImage* in, VipsImage** out, VipsCompassDirection direction, int width, int height, VipsExtend extend, double* background, int background_n);

int vipsgen_grey(VipsImage** out, int width, int height);
int vipsgen_grey_with_options(VipsImage** out, int width, int height, gboolean uchar);

int vipsgen_grid(VipsImage* in, VipsImage** out, int tile_height, int across, int down);

int vipsgen_hist_cum(VipsImage* in, VipsImage** out);

int vipsgen_hist_entropy(VipsImage* in, double* out);

int vipsgen_hist_equal(VipsImage* in, VipsImage** out);
int vipsgen_hist_equal_with_options(VipsImage* in, VipsImage** out, int band);

int vipsgen_hist_find(VipsImage* in, VipsImage** out);
int vipsgen_hist_find_with_options(VipsImage* in, VipsImage** out, int band);

int vipsgen_hist_find_indexed(VipsImage* in, VipsImage* index, VipsImage** out);
int vipsgen_hist_find_indexed_with_options(VipsImage* in, VipsImage* index, VipsImage** out, VipsCombine combine);

int vipsgen_hist_find_ndim(VipsImage* in, VipsImage** out);
int vipsgen_hist_find_ndim_with_options(VipsImage* in, VipsImage** out, int bins);

int vipsgen_hist_ismonotonic(VipsImage* in, gboolean* monotonic);

int vipsgen_hist_local(VipsImage* in, VipsImage** out, int width, int height);
int vipsgen_hist_local_with_options(VipsImage* in, VipsImage** out, int width, int height, int max_slope);

int vipsgen_hist_match(VipsImage* in, VipsImage* ref, VipsImage** out);

int vipsgen_hist_norm(VipsImage* in, VipsImage** out);

int vipsgen_hist_plot(VipsImage* in, VipsImage** out);

int vipsgen_hough_circle(VipsImage* in, VipsImage** out);
int vipsgen_hough_circle_with_options(VipsImage* in, VipsImage** out, int scale, int min_radius, int max_radius);

int vipsgen_hough_line(VipsImage* in, VipsImage** out);
int vipsgen_hough_line_with_options(VipsImage* in, VipsImage** out, int width, int height);

int vipsgen_identity(VipsImage** out);
int vipsgen_identity_with_options(VipsImage** out, int bands, gboolean ushort, int size);

int vipsgen_ifthenelse(VipsImage* cond, VipsImage* in1, VipsImage* in2, VipsImage** out);
int vipsgen_ifthenelse_with_options(VipsImage* cond, VipsImage* in1, VipsImage* in2, VipsImage** out, gboolean blend);

int vipsgen_insert(VipsImage* main, VipsImage* sub, VipsImage** out, int x, int y);
int vipsgen_insert_with_options(VipsImage* main, VipsImage* sub, VipsImage** out, int x, int y, gboolean expand, double* background, int background_n);

int vipsgen_invert(VipsImage* in, VipsImage** out);

int vipsgen_invertlut(VipsImage* in, VipsImage** out);
int vipsgen_invertlut_with_options(VipsImage* in, VipsImage** out, int size);

int vipsgen_join(VipsImage* in1, VipsImage* in2, VipsImage** out, VipsDirection direction);
int vipsgen_join_with_options(VipsImage* in1, VipsImage* in2, VipsImage** out, VipsDirection direction, gboolean expand, int shim, double* background, int background_n, VipsAlign align);

int vipsgen_jpegload(const char* filename, VipsImage** out);
int vipsgen_jpegload_with_options(const char* filename, VipsImage** out, int shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_jpegload_buffer(void* buf, size_t len, VipsImage** out);
int vipsgen_jpegload_buffer_with_options(void* buf, size_t len, VipsImage** out, int shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_jpegload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_jpegload_source_with_options(VipsSourceCustom* source, VipsImage** out, int shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_jpegsave(VipsImage* in, const char* filename);
int vipsgen_jpegsave_with_options(VipsImage* in, const char* filename, int Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, int quant_table, VipsForeignSubsample subsample_mode, int restart_interval, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_jpegsave_buffer(VipsImage* in, void** buf, size_t* len);
int vipsgen_jpegsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, int Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, int quant_table, VipsForeignSubsample subsample_mode, int restart_interval, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_jpegsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_jpegsave_target_with_options(VipsImage* in, VipsTargetCustom* target, int Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, int quant_table, VipsForeignSubsample subsample_mode, int restart_interval, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_labelregions(VipsImage* in, VipsImage** mask);

int vipsgen_linear(VipsImage* in, VipsImage** out, double* a, double* b, int n);
int vipsgen_linear_with_options(VipsImage* in, VipsImage** out, double* a, double* b, int n, gboolean uchar);

int vipsgen_linecache(VipsImage* in, VipsImage** out);
int vipsgen_linecache_with_options(VipsImage* in, VipsImage** out, int tile_height, VipsAccess access, gboolean threaded, gboolean persistent);

int vipsgen_logmat(VipsImage** out, double sigma, double min_ampl);
int vipsgen_logmat_with_options(VipsImage** out, double sigma, double min_ampl, gboolean separable, VipsPrecision precision);

int vipsgen_mapim(VipsImage* in, VipsImage** out, VipsImage* index);
int vipsgen_mapim_with_options(VipsImage* in, VipsImage** out, VipsImage* index, VipsInterpolate* interpolate, double* background, int background_n, gboolean premultiplied, VipsExtend extend);

int vipsgen_maplut(VipsImage* in, VipsImage** out, VipsImage* lut);
int vipsgen_maplut_with_options(VipsImage* in, VipsImage** out, VipsImage* lut, int band);

int vipsgen_mask_butterworth(VipsImage** out, int width, int height, double order, double frequency_cutoff, double amplitude_cutoff);
int vipsgen_mask_butterworth_with_options(VipsImage** out, int width, int height, double order, double frequency_cutoff, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_butterworth_band(VipsImage** out, int width, int height, double order, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff);
int vipsgen_mask_butterworth_band_with_options(VipsImage** out, int width, int height, double order, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_butterworth_ring(VipsImage** out, int width, int height, double order, double frequency_cutoff, double amplitude_cutoff, double ringwidth);
int vipsgen_mask_butterworth_ring_with_options(VipsImage** out, int width, int height, double order, double frequency_cutoff, double amplitude_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_fractal(VipsImage** out, int width, int height, double fractal_dimension);
int vipsgen_mask_fractal_with_options(VipsImage** out, int width, int height, double fractal_dimension, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_gaussian(VipsImage** out, int width, int height, double frequency_cutoff, double amplitude_cutoff);
int vipsgen_mask_gaussian_with_options(VipsImage** out, int width, int height, double frequency_cutoff, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_gaussian_band(VipsImage** out, int width, int height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff);
int vipsgen_mask_gaussian_band_with_options(VipsImage** out, int width, int height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_gaussian_ring(VipsImage** out, int width, int height, double frequency_cutoff, double amplitude_cutoff, double ringwidth);
int vipsgen_mask_gaussian_ring_with_options(VipsImage** out, int width, int height, double frequency_cutoff, double amplitude_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_ideal(VipsImage** out, int width, int height, double frequency_cutoff);
int vipsgen_mask_ideal_with_options(VipsImage** out, int width, int height, double frequency_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_ideal_band(VipsImage** out, int width, int height, double frequency_cutoff_x, double frequency_cutoff_y, double radius);
int vipsgen_mask_ideal_band_with_options(VipsImage** out, int width, int height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_mask_ideal_ring(VipsImage** out, int width, int height, double frequency_cutoff, double ringwidth);
int vipsgen_mask_ideal_ring_with_options(VipsImage** out, int width, int height, double frequency_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int vipsgen_match(VipsImage* ref, VipsImage* sec, VipsImage** out, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2);
int vipsgen_match_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2, int hwindow, int harea, gboolean search, VipsInterpolate* interpolate);

int vipsgen_math(VipsImage* in, VipsImage** out, VipsOperationMath math);

int vipsgen_math2(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationMath2 math2);

int vipsgen_math2_const(VipsImage* in, VipsImage** out, VipsOperationMath2 math2, double* c, int n);

int vipsgen_matrixinvert(VipsImage* in, VipsImage** out);

int vipsgen_matrixload(const char* filename, VipsImage** out);
int vipsgen_matrixload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_matrixload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_matrixload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_matrixprint(VipsImage* in);
int vipsgen_matrixprint_with_options(VipsImage* in, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_matrixsave(VipsImage* in, const char* filename);
int vipsgen_matrixsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_matrixsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_matrixsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_max(VipsImage* in, double* out);
int vipsgen_max_with_options(VipsImage* in, double* out, int size);

int vipsgen_maxpair(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_measure(VipsImage* in, VipsImage** out, int h, int v);
int vipsgen_measure_with_options(VipsImage* in, VipsImage** out, int h, int v, int left, int top, int width, int height);

int vipsgen_merge(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int dx, int dy);
int vipsgen_merge_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int dx, int dy, int mblend);

int vipsgen_min(VipsImage* in, double* out);
int vipsgen_min_with_options(VipsImage* in, double* out, int size);

int vipsgen_minpair(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_morph(VipsImage* in, VipsImage** out, VipsImage* mask, VipsOperationMorphology morph);

int vipsgen_mosaic(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int xref, int yref, int xsec, int ysec);
int vipsgen_mosaic_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int xref, int yref, int xsec, int ysec, int hwindow, int harea, int mblend, int bandno);

int vipsgen_mosaic1(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2);
int vipsgen_mosaic1_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, int xr1, int yr1, int xs1, int ys1, int xr2, int yr2, int xs2, int ys2, int hwindow, int harea, gboolean search, VipsInterpolate* interpolate, int mblend);

int vipsgen_msb(VipsImage* in, VipsImage** out);
int vipsgen_msb_with_options(VipsImage* in, VipsImage** out, int band);

int vipsgen_multiply(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_percent(VipsImage* in, double percent, int* threshold);

int vipsgen_perlin(VipsImage** out, int width, int height);
int vipsgen_perlin_with_options(VipsImage** out, int width, int height, int cell_size, gboolean uchar, int seed);

int vipsgen_phasecor(VipsImage* in, VipsImage* in2, VipsImage** out);

int vipsgen_pngload(const char* filename, VipsImage** out);
int vipsgen_pngload_with_options(const char* filename, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_pngload_buffer(void* buf, size_t len, VipsImage** out);
int vipsgen_pngload_buffer_with_options(void* buf, size_t len, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_pngload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_pngload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_pngsave(VipsImage* in, const char* filename);
int vipsgen_pngsave_with_options(VipsImage* in, const char* filename, int compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, int Q, double dither, int bitdepth, int effort, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_pngsave_buffer(VipsImage* in, void** buf, size_t* len);
int vipsgen_pngsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, int compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, int Q, double dither, int bitdepth, int effort, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_pngsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_pngsave_target_with_options(VipsImage* in, VipsTargetCustom* target, int compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, int Q, double dither, int bitdepth, int effort, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_ppmload(const char* filename, VipsImage** out);
int vipsgen_ppmload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_ppmload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_ppmload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_ppmsave(VipsImage* in, const char* filename);
int vipsgen_ppmsave_with_options(VipsImage* in, const char* filename, VipsForeignPpmFormat format, gboolean ascii, int bitdepth, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_ppmsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_ppmsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignPpmFormat format, gboolean ascii, int bitdepth, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_premultiply(VipsImage* in, VipsImage** out);
int vipsgen_premultiply_with_options(VipsImage* in, VipsImage** out, double max_alpha);

int vipsgen_prewitt(VipsImage* in, VipsImage** out);

int vipsgen_profile(VipsImage* in, VipsImage** columns, VipsImage** rows);

int vipsgen_profile_load(const char* name, VipsBlob** profile);

int vipsgen_project(VipsImage* in, VipsImage** columns, VipsImage** rows);

int vipsgen_quadratic(VipsImage* in, VipsImage** out, VipsImage* coeff);
int vipsgen_quadratic_with_options(VipsImage* in, VipsImage** out, VipsImage* coeff, VipsInterpolate* interpolate);

int vipsgen_rad2float(VipsImage* in, VipsImage** out);

int vipsgen_radload(const char* filename, VipsImage** out);
int vipsgen_radload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_radload_buffer(void* buf, size_t len, VipsImage** out);
int vipsgen_radload_buffer_with_options(void* buf, size_t len, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_radload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_radload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_radsave(VipsImage* in, const char* filename);
int vipsgen_radsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_radsave_buffer(VipsImage* in, void** buf, size_t* len);
int vipsgen_radsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_radsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_radsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_rank(VipsImage* in, VipsImage** out, int width, int height, int index);

int vipsgen_rawload(const char* filename, VipsImage** out, int width, int height, int bands);
int vipsgen_rawload_with_options(const char* filename, VipsImage** out, int width, int height, int bands, guint64 offset, VipsBandFormat format, VipsInterpretation interpretation, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_rawsave(VipsImage* in, const char* filename);
int vipsgen_rawsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_rawsave_buffer(VipsImage* in, void** buf, size_t* len);
int vipsgen_rawsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_rawsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_rawsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_recomb(VipsImage* in, VipsImage** out, VipsImage* m);

int vipsgen_reduce(VipsImage* in, VipsImage** out, double hshrink, double vshrink);
int vipsgen_reduce_with_options(VipsImage* in, VipsImage** out, double hshrink, double vshrink, VipsKernel kernel, double gap);

int vipsgen_reduceh(VipsImage* in, VipsImage** out, double hshrink);
int vipsgen_reduceh_with_options(VipsImage* in, VipsImage** out, double hshrink, VipsKernel kernel, double gap);

int vipsgen_reducev(VipsImage* in, VipsImage** out, double vshrink);
int vipsgen_reducev_with_options(VipsImage* in, VipsImage** out, double vshrink, VipsKernel kernel, double gap);

int vipsgen_relational(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationRelational relational);

int vipsgen_relational_const(VipsImage* in, VipsImage** out, VipsOperationRelational relational, double* c, int n);

int vipsgen_remainder(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_remainder_const(VipsImage* in, VipsImage** out, double* c, int n);

int vipsgen_replicate(VipsImage* in, VipsImage** out, int across, int down);

int vipsgen_resize(VipsImage* in, VipsImage** out, double scale);
int vipsgen_resize_with_options(VipsImage* in, VipsImage** out, double scale, VipsKernel kernel, double gap, double vscale);

int vipsgen_rot(VipsImage* in, VipsImage** out, VipsAngle angle);

int vipsgen_rot45(VipsImage* in, VipsImage** out);
int vipsgen_rot45_with_options(VipsImage* in, VipsImage** out, VipsAngle45 angle);

int vipsgen_rotate(VipsImage* in, VipsImage** out, double angle);
int vipsgen_rotate_with_options(VipsImage* in, VipsImage** out, double angle, VipsInterpolate* interpolate, double* background, int background_n, double odx, double ody, double idx, double idy);

int vipsgen_round(VipsImage* in, VipsImage** out, VipsOperationRound round);

int vipsgen_sRGB2HSV(VipsImage* in, VipsImage** out);

int vipsgen_sRGB2scRGB(VipsImage* in, VipsImage** out);

int vipsgen_scRGB2BW(VipsImage* in, VipsImage** out);
int vipsgen_scRGB2BW_with_options(VipsImage* in, VipsImage** out, int depth);

int vipsgen_scRGB2XYZ(VipsImage* in, VipsImage** out);

int vipsgen_scRGB2sRGB(VipsImage* in, VipsImage** out);
int vipsgen_scRGB2sRGB_with_options(VipsImage* in, VipsImage** out, int depth);

int vipsgen_scale(VipsImage* in, VipsImage** out);
int vipsgen_scale_with_options(VipsImage* in, VipsImage** out, double exp, gboolean log);

int vipsgen_scharr(VipsImage* in, VipsImage** out);

int vipsgen_sdf(VipsImage** out, int width, int height, VipsSdfShape shape);
int vipsgen_sdf_with_options(VipsImage** out, int width, int height, VipsSdfShape shape, double r, double* a, int a_n, double* b, int b_n, double* corners, int corners_n);

int vipsgen_sequential(VipsImage* in, VipsImage** out);
int vipsgen_sequential_with_options(VipsImage* in, VipsImage** out, int tile_height);

int vipsgen_sharpen(VipsImage* in, VipsImage** out);
int vipsgen_sharpen_with_options(VipsImage* in, VipsImage** out, double sigma, double x1, double y2, double y3, double m1, double m2);

int vipsgen_shrink(VipsImage* in, VipsImage** out, double hshrink, double vshrink);
int vipsgen_shrink_with_options(VipsImage* in, VipsImage** out, double hshrink, double vshrink, gboolean ceil);

int vipsgen_shrinkh(VipsImage* in, VipsImage** out, int hshrink);
int vipsgen_shrinkh_with_options(VipsImage* in, VipsImage** out, int hshrink, gboolean ceil);

int vipsgen_shrinkv(VipsImage* in, VipsImage** out, int vshrink);
int vipsgen_shrinkv_with_options(VipsImage* in, VipsImage** out, int vshrink, gboolean ceil);

int vipsgen_sign(VipsImage* in, VipsImage** out);

int vipsgen_similarity(VipsImage* in, VipsImage** out);
int vipsgen_similarity_with_options(VipsImage* in, VipsImage** out, double scale, double angle, VipsInterpolate* interpolate, double* background, int background_n, double odx, double ody, double idx, double idy);

int vipsgen_sines(VipsImage** out, int width, int height);
int vipsgen_sines_with_options(VipsImage** out, int width, int height, gboolean uchar, double hfreq, double vfreq);

int vipsgen_smartcrop(VipsImage* input, VipsImage** out, int width, int height);
int vipsgen_smartcrop_with_options(VipsImage* input, VipsImage** out, int width, int height, VipsInteresting interesting, gboolean premultiplied);

int vipsgen_sobel(VipsImage* in, VipsImage** out);

int vipsgen_spcor(VipsImage* in, VipsImage* ref, VipsImage** out);

int vipsgen_spectrum(VipsImage* in, VipsImage** out);

int vipsgen_stats(VipsImage* in, VipsImage** out);

int vipsgen_stdif(VipsImage* in, VipsImage** out, int width, int height);
int vipsgen_stdif_with_options(VipsImage* in, VipsImage** out, int width, int height, double s0, double b, double m0, double a);

int vipsgen_subsample(VipsImage* input, VipsImage** out, int xfac, int yfac);
int vipsgen_subsample_with_options(VipsImage* input, VipsImage** out, int xfac, int yfac, gboolean point);

int vipsgen_subtract(VipsImage* left, VipsImage* right, VipsImage** out);

int vipsgen_sum(VipsImage** in, VipsImage** out, int n);

int vipsgen_switch(VipsImage** tests, VipsImage** out, int n);

int vipsgen_system(const char* cmd_format);
int vipsgen_system_with_options(const char* cmd_format, VipsImage** in, int in_n, const char* out_format, const char* in_format);

int vipsgen_thumbnail(const char* filename, VipsImage** out, int width);
int vipsgen_thumbnail_with_options(const char* filename, VipsImage** out, int width, int height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* import_profile, const char* export_profile, VipsIntent intent, VipsFailOn fail_on);

int vipsgen_thumbnail_buffer(void* buf, size_t len, VipsImage** out, int width);
int vipsgen_thumbnail_buffer_with_options(void* buf, size_t len, VipsImage** out, int width, const char* option_string, int height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* import_profile, const char* export_profile, VipsIntent intent, VipsFailOn fail_on);

int vipsgen_thumbnail_image(VipsImage* in, VipsImage** out, int width);
int vipsgen_thumbnail_image_with_options(VipsImage* in, VipsImage** out, int width, int height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* import_profile, const char* export_profile, VipsIntent intent, VipsFailOn fail_on);

int vipsgen_thumbnail_source(VipsSourceCustom* source, VipsImage** out, int width);
int vipsgen_thumbnail_source_with_options(VipsSourceCustom* source, VipsImage** out, int width, const char* option_string, int height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* import_profile, const char* export_profile, VipsIntent intent, VipsFailOn fail_on);

int vipsgen_tilecache(VipsImage* in, VipsImage** out);
int vipsgen_tilecache_with_options(VipsImage* in, VipsImage** out, int tile_width, int tile_height, int max_tiles, VipsAccess access, gboolean threaded, gboolean persistent);

int vipsgen_tonelut(VipsImage** out);
int vipsgen_tonelut_with_options(VipsImage** out, int in_max, int out_max, double Lb, double Lw, double Ps, double Pm, double Ph, double S, double M, double H);

int vipsgen_transpose3d(VipsImage* in, VipsImage** out);
int vipsgen_transpose3d_with_options(VipsImage* in, VipsImage** out, int page_height);

int vipsgen_unpremultiply(VipsImage* in, VipsImage** out);
int vipsgen_unpremultiply_with_options(VipsImage* in, VipsImage** out, double max_alpha, int alpha_band);

int vipsgen_vipsload(const char* filename, VipsImage** out);
int vipsgen_vipsload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_vipsload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_vipsload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_vipssave(VipsImage* in, const char* filename);
int vipsgen_vipssave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_vipssave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_vipssave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_webpload(const char* filename, VipsImage** out);
int vipsgen_webpload_with_options(const char* filename, VipsImage** out, int page, int n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_webpload_buffer(void* buf, size_t len, VipsImage** out);
int vipsgen_webpload_buffer_with_options(void* buf, size_t len, VipsImage** out, int page, int n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_webpload_source(VipsSourceCustom* source, VipsImage** out);
int vipsgen_webpload_source_with_options(VipsSourceCustom* source, VipsImage** out, int page, int n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int vipsgen_webpsave(VipsImage* in, const char* filename);
int vipsgen_webpsave_with_options(VipsImage* in, const char* filename, int Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, int alpha_q, gboolean min_size, int kmin, int kmax, int effort, int target_size, gboolean mixed, gboolean smart_deblock, int passes, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_webpsave_buffer(VipsImage* in, void** buf, size_t* len);
int vipsgen_webpsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, int Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, int alpha_q, gboolean min_size, int kmin, int kmax, int effort, int target_size, gboolean mixed, gboolean smart_deblock, int passes, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_webpsave_target(VipsImage* in, VipsTargetCustom* target);
int vipsgen_webpsave_target_with_options(VipsImage* in, VipsTargetCustom* target, int Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, int alpha_q, gboolean min_size, int kmin, int kmax, int effort, int target_size, gboolean mixed, gboolean smart_deblock, int passes, VipsForeignKeep keep, double* background, int background_n, int page_height, const char* profile);

int vipsgen_worley(VipsImage** out, int width, int height);
int vipsgen_worley_with_options(VipsImage** out, int width, int height, int cell_size, int seed);

int vipsgen_wrap(VipsImage* in, VipsImage** out);
int vipsgen_wrap_with_options(VipsImage* in, VipsImage** out, int x, int y);

int vipsgen_xyz(VipsImage** out, int width, int height);
int vipsgen_xyz_with_options(VipsImage** out, int width, int height, int csize, int dsize, int esize);

int vipsgen_zone(VipsImage** out, int width, int height);
int vipsgen_zone_with_options(VipsImage** out, int width, int height, gboolean uchar);

int vipsgen_zoom(VipsImage* input, VipsImage** out, int xfac, int yfac);


// Custom operations

int vipsgen_image_new_from_source(VipsSourceCustom *source, VipsImage **out);
int vipsgen_image_new_from_source_with_option(VipsSourceCustom *source, VipsImage **out, const char *option_string);
int vipsgen_image_new_from_file(const char *name, VipsImage **out);
int vipsgen_image_new_from_buffer(const void *buf, size_t len, VipsImage **out);
int vipsgen_image_new_from_buffer_with_option(const void *buf, size_t len, VipsImage **out, const char *option_string);
int vipsgen_image_new_from_memory(const void *buf, size_t len, int width, int height, int bands, VipsImage **out);
void vipsgen_clear_image(VipsImage **image);

int vipsgen_remove_exif(VipsImage *in, VipsImage **out);
int vipsgen_embed_multi_page(VipsImage *in, VipsImage **out, int left, int top, int width, int height, int extend);
int vipsgen_embed_multi_page_background(VipsImage *in, VipsImage **out, int left, int top, int width, int height, double r, double g, double b, double a);
int vipsgen_extract_area_multi_page(VipsImage *in, VipsImage **out, int left, int top, int width, int height);
int vipsgen_rot_multi_page(VipsImage *in, VipsImage **out, VipsAngle angle);
int vipsgen_label(VipsImage *in, VipsImage **out, const char *text, const char *font, int x, int y, int size, VipsAlign align, double r, double g, double b, float opacity);
